#!/usr/bin/node
// Display the status code of a GET request.

const request = require('request');
const url = process.argv[2];
let x = 0;
request.get(url, function (_error, response) {
  let charecter = JSON.parse(response.body).results
  for (const i of charecter) {
    if ('https://swapi-api.alx-tools.com/api/people/18/' in i.characters === true) {
      x += 1;
      console.log(i.characters)
    }
  }
console.log(x);
});
